### ISSUE TITLE
Ability to change web browser userAgent string

### ISSUE THREAD

**Issue by nhinze** [boxeehacks/boxeehack#185] opened 2012-12-11 20:50 UTC
Not sure if that is possible or not, but it would be great to be able to change the web browser userAgent string to simulate an iPhone or iPad. This way the Boxee would be able to get the HTML5 video instead of Flash for a lot of sites where Flash doesn't work on the Boxee anymore.

**Comment by boxeehacks** [comment] 2012-12-11 22:24
Duplicate of #137

unfortunately not possible

**Closed as completed by boxeehacks** 2012-12-11 22:24 UTC
