### ISSUE TITLE
Feature request - Browser user-agent edit

### ISSUE THREAD

**Issue by dembonez** [boxeehacks/boxeehack#137] opened 2012-12-08 16:44 UTC
Would it be possible to change the user-agent string the Boxee Web Browser sends to identify itself?  If so, we could use that to show webservers (such as hulu) that the browser is a standard desktop version of IE or Firefox.

**Comment by boxeehacks** [comment] 2012-12-08 20:05
Duplicate of #134 (sort of ;) )

**Closed as completed by boxeehacks** 2012-12-08 20:05 UTC
