### ISSUE TITLE
 Cannot shut down Boxee Box with release 1.4.1

### ISSUE THREAD

**Issue by oliviersv** [boxeehacks/boxeehack#308] opened 2013-01-03 21:46 UTC
Hello,

 I  cannot shut down Boxee Box with the last version. it always reboots.

I checked and I dindn't have this problem when I desactivated the hack.

I dind't have this problem too with earlier version.

Regards,

**Comment by oliviersv** [comment] 2013-01-03 22:13
here is the log :

23:07:16.881 T:3072382752 M:479428608  NOTICE: Storing total System Uptime
23:07:16.881 T:3072382752 M:479428608  NOTICE: Saving settings
23:07:16.898 T:3072382752 M:479428608  NOTICE: Boxee Metadata Engine, stopping....
23:07:16.899 T:3072382752 M:479428608    INFO: Boxee Metadata Resolver, stopping...
23:07:16.899 T:3072382752 M:479428608    INFO: Boxee Metadata Resolver Music, stopping...
23:07:16.899 T:3072382752 M:479428608  NOTICE: Stopping audio processor
23:07:16.900 T:3072382752 M:479428608  NOTICE: Stopping video processor
23:07:17.468 T:2955934608 M:479449088   DEBUG: Boxee: 03/01/13 22:07:17.4679#DEBUG#bxmetadataengine.cpp:396(EngineThread)#BXMetadataEngine::EngineThread,  Engine, exiting...(resolver)
23:07:17.469 T:3072382752 M:479449088   DEBUG: Boxee: 03/01/13 22:07:17.4692#DEBUG#bxmetadataengine.cpp:158(Stop)#Boxee Metadata Engine, stoppped....
23:07:17.469 T:3072382752 M:479449088  NOTICE: stop all
23:07:17.469 T:3072382752 M:479449088   DEBUG: NetworkMessage - Signaling network services to stop
23:07:17.470 T:3072382752 M:479449088  NOTICE: Webserver: Stopping...
23:07:17.470 T:3072382752 M:479449088  NOTICE: ES: Stopping event server
23:07:17.470 T:3072382752 M:479449088   DEBUG: CZeroconfAvahi::doRemoveService named: servers.eventserver
23:07:17.474 T:3072382752 M:479449088   DEBUG: NetworkMessage - Waiting for network services to stop
23:07:17.475 T:3072382752 M:479449088  NOTICE: stopping zeroconf publishing
23:07:17.491 T:3072382752 M:479457280   DEBUG: CLastfmScrobbler: Journal with 0 entries saved to special://masterprofile/profiles/e/LastfmScrobbler.xml
23:07:17.492 T:3072382752 M:479457280   DEBUG: CLibrefmScrobbler: Journal with 0 entries saved to special://masterprofile/profiles/LibrefmScrobbler.xml
23:07:18.227 T:3017046928 M:479457280   DEBUG: WebServer:Exiting thread sockReady=0, sockSelect=0.
23:07:18.228 T:3017046928 M:479457280   DEBUG: WebServer:OnExit - Exit web server.
23:07:18.229 T:3017046928 M:479457280   DEBUG: Thread 3017046928 terminating
23:07:18.229 T:3072382752 M:479457280   DEBUG: xbmcHttpShim ends
23:07:18.229 T:3072382752 M:479457280   DEBUG: xbmcHttp ends
23:07:18.230 T:3072382752 M:479457280  NOTICE: Webserver: Stopped...
23:07:18.243 T:3014941584 M:479465472  NOTICE: ES: UDP Event server stopped
23:07:18.244 T:3014941584 M:479465472   DEBUG: Thread 3014941584 terminating
23:07:18.245 T:3070135184 M:479465472   DEBUG: Thread 3070135184 terminating
23:07:18.245 T:3072382752 M:479465472  NOTICE: stop zeroconf browser
23:07:18.246 T:3072382752 M:479465472   DEBUG: CZeroconfAvahi::~CZeroconfAvahi() Going down! cleaning up...
23:07:18.248 T:3072382752 M:479465472  NOTICE: clean cached files!
23:07:18.249 T:3072382752 M:479465472  NOTICE: unload skin
23:07:18.249 T:3072382752 M:479465472   DEBUG: ------ Window Deinit (Home.xml) ------
23:07:18.251 T:3072382752 M:479465472   DEBUG: ------ Window Deinit (DialogButtonMenu.xml) ------
23:07:18.253 T:3072382752 M:479465472   DEBUG: ------ Window Deinit (boxee_browse_menu.xml) ------
23:07:18.255 T:3072382752 M:479465472   DEBUG: ------ Window Deinit (Pointer.xml) ------
23:07:18.257 T:3072382752 M:479490048   DEBUG: ------ Window Deinit (DialogMuteBug.xml) ------
23:07:18.257 T:3072382752 M:479490048   DEBUG: Cleanup: Having to cleanup texture black.png
23:07:18.258 T:3072382752 M:479490048   DEBUG: Cleanup: Having to cleanup texture browse/thumbnail-bg-off.png
23:07:18.258 T:3072382752 M:479490048   DEBUG: Cleanup: Having to cleanup texture browse/thumbnail-bg-on.png
23:07:18.258 T:3072382752 M:479490048   DEBUG: Cleanup: Having to cleanup texture icons/icon-home-live-tv.png
23:07:18.259 T:3072382752 M:479490048   DEBUG: Cleanup: Having to cleanup texture icons/icon-home-friends.png
23:07:18.259 T:3072382752 M:479490048   DEBUG: Cleanup: Having to cleanup texture icons/icon-home-watch-later.png
23:07:18.260 T:3072382752 M:479617024   DEBUG: Cleanup: Having to cleanup texture icons/icon-home-shows.png
23:07:18.260 T:3072382752 M:479744000   DEBUG: Cleanup: Having to cleanup texture icons/icon-home-movies.png
23:07:18.260 T:3072382752 M:479870976   DEBUG: Cleanup: Having to cleanup texture icons/icon-home-apps.png
23:07:18.261 T:3072382752 M:479997952   DEBUG: Cleanup: Having to cleanup texture icons/icon-home-files.png
23:07:18.261 T:3072382752 M:479997952   DEBUG: Cleanup: Having to cleanup texture icons/icon-home-web.png
23:07:18.262 T:3072382752 M:480124928   DEBUG: Cleanup: Having to cleanup texture mainmenu/graphic-icon-home.png
23:07:18.262 T:3072382752 M:480124928   DEBUG: Cleanup: Having to cleanup texture mainmenu/graphic-icon-history.png
23:07:18.262 T:3072382752 M:480129024   DEBUG: Cleanup: Having to cleanup texture mainmenu/graphic-icon-settings.png
23:07:18.263 T:3072382752 M:480256000   DEBUG: Cleanup: Having to cleanup texture mainmenu/graphic-icon-exit.png
23:07:18.263 T:3072382752 M:480256000   DEBUG: Cleanup: Having to cleanup texture nofocus.png
23:07:18.263 T:3072382752 M:480256000   DEBUG: Cleanup: Having to cleanup texture defaultloading.gif
23:07:18.264 T:3072382752 M:480256000   DEBUG: Cleanup: Having to cleanup texture masks/thumb_square_manage.png
23:07:18.264 T:3072382752 M:480256000   DEBUG: Cleanup: Having to cleanup texture masks/thumb_border.png
23:07:18.265 T:3072382752 M:480256000   DEBUG: Cleanup: Having to cleanup texture masks/provider_mask.png
23:07:18.265 T:3072382752 M:480256000   DEBUG: Cleanup: Having to cleanup texture button_menu_on.png
23:07:18.265 T:3072382752 M:480256000   DEBUG: Cleanup: Having to cleanup texture loading_placeholder.png
23:07:18.266 T:3072382752 M:480256000   DEBUG: Cleanup: Having to cleanup texture masks/thumb_background_on.png
23:07:18.266 T:3072382752 M:480256000   DEBUG: Cleanup: Having to cleanup texture masks/thumb_background.png
23:07:18.266 T:3072382752 M:480256000   DEBUG: Cleanup: Having to cleanup texture masks/default_video.png
23:07:18.266 T:3072382752 M:480256000   DEBUG: Cleanup: Having to cleanup texture default_video.png
23:07:18.267 T:3072382752 M:480890880   DEBUG: Cleanup: Having to cleanup texture masks/default_photo.png
23:07:18.267 T:3072382752 M:480890880   DEBUG: Cleanup: Having to cleanup texture masks/default_music.png
23:07:18.268 T:3072382752 M:480890880   DEBUG: Cleanup: Having to cleanup texture masks/default_general.png
23:07:18.268 T:3072382752 M:480890880   DEBUG: Cleanup: Having to cleanup texture masks/default_folder.png
23:07:18.268 T:3072382752 M:480890880   DEBUG: Cleanup: Having to cleanup texture masks/10b9f2.png
23:07:18.268 T:3072382752 M:480890880   DEBUG: Cleanup: Having to cleanup texture masks/1c8aaf.png
23:07:18.269 T:3072382752 M:480890880   DEBUG: Cleanup: Having to cleanup texture masks/464646.png
23:07:18.269 T:3072382752 M:480890880   DEBUG: Cleanup: Having to cleanup texture masks/565a57.png
23:07:18.269 T:3072382752 M:480890880   DEBUG: Cleanup: Having to cleanup texture masks/686c69.png
23:07:18.269 T:3072382752 M:480890880   DEBUG: Cleanup: Having to cleanup texture masks/777d79.png
23:07:18.270 T:3072382752 M:480890880   DEBUG: Cleanup: Having to cleanup texture masks/868d89.png
23:07:18.270 T:3072382752 M:480890880   DEBUG: Cleanup: Having to cleanup texture browse_menu_dialog_background.png
23:07:18.270 T:3072382752 M:480890880   DEBUG: Cleanup: Having to cleanup texture button_8_pixel.png
23:07:18.270 T:3072382752 M:480890880   DEBUG: Cleanup: Having to cleanup texture background/background.jpg
23:07:18.273 T:3072382752 M:489279488   DEBUG: Cleanup: Having to cleanup texture background/background-mask-episodes.png
23:07:18.274 T:3072382752 M:489914368   DEBUG: Cleanup: Having to cleanup texture background/bg-browse.jpg
23:07:18.276 T:3072382752 M:498167808   DEBUG: Cleanup: Having to cleanup texture background/window-bg-transparent.png
23:07:18.277 T:3072382752 M:498167808   DEBUG: Cleanup: Having to cleanup texture browse_menu_dialog_button_focus2.png
23:07:18.277 T:3072382752 M:498167808   DEBUG: Cleanup: Having to cleanup texture browse_menu_dialog_button_focus.png
23:07:18.608 T:3072382752 M:498167808   DEBUG: Cleanup: Having to cleanup texture browse_menu_dialog_edit_focus.png
23:07:18.608 T:3072382752 M:498167808   DEBUG: Cleanup: Having to cleanup texture browse_menu_dialog_edit.png
23:07:18.608 T:3072382752 M:498167808   DEBUG: Cleanup: Having to cleanup texture icons/icon_battery_low_small.png
23:07:18.609 T:3072382752 M:498167808   DEBUG: Cleanup: Having to cleanup texture icons/icon_browse_menu_apps.png
23:07:18.609 T:3072382752 M:498167808   DEBUG: Cleanup: Having to cleanup texture icons/icon_browse_menu_clock.png
23:07:18.609 T:3072382752 M:498167808   DEBUG: Cleanup: Having to cleanup texture icons/icon_browse_menu_exit.png
23:07:18.609 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture icons/icon_browse_menu_home.png
23:07:18.610 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture icons/icon_browse_menu_movies.png
23:07:18.610 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture icons/icon_browse_menu_settings.png
23:07:18.610 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture icons/icon_browse_menu_shows.png
23:07:18.611 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture icons/icon_browse_menu_vpn.png
23:07:18.611 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture icons/icon_download_update.png
23:07:18.611 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture icons/icon_play.png
23:07:18.611 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture menu_dialog_background_bottom.png
23:07:18.612 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture menu_dialog_background.png
23:07:18.612 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture menu_dialog_background_top.png
23:07:18.612 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture menu_dialog_button_tab.png
23:07:18.612 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture white.png
23:07:18.613 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010001.png
23:07:18.613 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010002.png
23:07:18.613 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010003.png
23:07:18.614 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010004.png
23:07:18.614 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010005.png
23:07:18.614 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010006.png
23:07:18.615 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010007.png
23:07:18.615 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010008.png
23:07:18.615 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010009.png
23:07:18.616 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010010.png
23:07:18.616 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010011.png
23:07:18.616 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010012.png
23:07:18.617 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010013.png
23:07:18.617 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010014.png
23:07:18.617 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010015.png
23:07:18.617 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010016.png
23:07:18.618 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010017.png
23:07:18.618 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010018.png
23:07:18.618 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010019.png
23:07:18.619 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010020.png
23:07:18.619 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010021.png
23:07:18.619 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010022.png
23:07:18.619 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010023.png
23:07:18.620 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010024.png
23:07:18.620 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010025.png
23:07:18.620 T:3072382752 M:498171904   DEBUG: Cleanup: Having to cleanup texture loading_small/010026.png
23:07:18.620 T:3072382752 M:498176000   DEBUG: Cleanup: Having to cleanup texture loading_small/010027.png
23:07:18.621 T:3072382752 M:498176000   DEBUG: Cleanup: Having to cleanup texture loading_small/010028.png
23:07:18.951 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010029.png
23:07:18.952 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010030.png
23:07:18.952 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010031.png
23:07:18.952 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010032.png
23:07:18.952 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010033.png
23:07:18.953 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010034.png
23:07:18.953 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010035.png
23:07:18.953 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010036.png
23:07:18.954 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010037.png
23:07:18.954 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010038.png
23:07:18.954 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010039.png
23:07:18.955 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010040.png
23:07:18.955 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010041.png
23:07:18.955 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010042.png
23:07:18.956 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010043.png
23:07:18.956 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010044.png
23:07:18.956 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010045.png
23:07:18.957 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010046.png
23:07:18.957 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010047.png
23:07:18.957 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010048.png
23:07:18.958 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010049.png
23:07:18.958 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010050.png
23:07:18.958 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010051.png
23:07:18.958 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010052.png
23:07:18.959 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010053.png
23:07:18.959 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010054.png
23:07:18.959 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010055.png
23:07:18.959 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010056.png
23:07:18.960 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010057.png
23:07:18.960 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010058.png
23:07:18.960 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010059.png
23:07:18.960 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading_small/010060.png
23:07:18.961 T:3072382752 M:498184192   DEBUG: Cleanup: Having to cleanup texture loading/010001.png
23:07:18.961 T:3072382752 M:498438144   DEBUG: Cleanup: Having to cleanup texture loading/010002.png
23:07:18.962 T:3072382752 M:498692096   DEBUG: Cleanup: Having to cleanup texture loading/010003.png
23:07:18.962 T:3072382752 M:498946048   DEBUG: Cleanup: Having to cleanup texture loading/010004.png
23:07:18.963 T:3072382752 M:499204096   DEBUG: Cleanup: Having to cleanup texture loading/010005.png
23:07:18.963 T:3072382752 M:499458048   DEBUG: Cleanup: Having to cleanup texture loading/010006.png
23:07:18.963 T:3072382752 M:499712000   DEBUG: Cleanup: Having to cleanup texture loading/010007.png
23:07:18.964 T:3072382752 M:499965952   DEBUG: Cleanup: Having to cleanup texture loading/010008.png
23:07:18.965 T:3072382752 M:500346880   DEBUG: Cleanup: Having to cleanup texture loading/010009.png
23:07:18.965 T:3072382752 M:500600832   DEBUG: Cleanup: Having to cleanup texture loading/010010.png
23:07:18.966 T:3072382752 M:500854784   DEBUG: Cleanup: Having to cleanup texture loading/010011.png
23:07:18.966 T:3072382752 M:501108736   DEBUG: Cleanup: Having to cleanup texture loading/010012.png
23:07:18.967 T:3072382752 M:501362688   DEBUG: Cleanup: Having to cleanup texture loading/010013.png
23:07:18.967 T:3072382752 M:501616640   DEBUG: Cleanup: Having to cleanup texture loading/010014.png
23:07:18.968 T:3072382752 M:501870592   DEBUG: Cleanup: Having to cleanup texture loading/010015.png
23:07:18.968 T:3072382752 M:502124544   DEBUG: Cleanup: Having to cleanup texture loading/010016.png
23:07:18.969 T:3072382752 M:502378496   DEBUG: Cleanup: Having to cleanup texture loading/010017.png
23:07:18.969 T:3072382752 M:502632448   DEBUG: Cleanup: Having to cleanup texture loading/010018.png
23:07:19.301 T:3072382752 M:502886400   DEBUG: Cleanup: Having to cleanup texture loading/010019.png
23:07:19.301 T:3072382752 M:503140352   DEBUG: Cleanup: Having to cleanup texture loading/010020.png
23:07:19.302 T:3072382752 M:503394304   DEBUG: Cleanup: Having to cleanup texture loading/010021.png
23:07:19.302 T:3072382752 M:503648256   DEBUG: Cleanup: Having to cleanup texture loading/010022.png
23:07:19.302 T:3072382752 M:503902208   DEBUG: Cleanup: Having to cleanup texture loading/010023.png
23:07:19.303 T:3072382752 M:504283136   DEBUG: Cleanup: Having to cleanup texture loading/010024.png
23:07:19.303 T:3072382752 M:504537088   DEBUG: Cleanup: Having to cleanup texture loading/010025.png
23:07:19.304 T:3072382752 M:504791040   DEBUG: Cleanup: Having to cleanup texture loading/010026.png
23:07:19.304 T:3072382752 M:505044992   DEBUG: Cleanup: Having to cleanup texture loading/010027.png
23:07:19.305 T:3072382752 M:505298944   DEBUG: Cleanup: Having to cleanup texture loading/010028.png
23:07:19.305 T:3072382752 M:505552896   DEBUG: Cleanup: Having to cleanup texture loading/010029.png
23:07:19.306 T:3072382752 M:505806848   DEBUG: Cleanup: Having to cleanup texture loading/010030.png
23:07:19.307 T:3072382752 M:506060800   DEBUG: Cleanup: Having to cleanup texture browse/thumbnail-default-landscape.png
23:07:19.307 T:3072382752 M:506568704   DEBUG: Cleanup: Having to cleanup texture special://masterprofile/profiles//Thumbnails/Pictures/a/a8fbfce1.tbn
23:07:19.308 T:3072382752 M:507457536   DEBUG: Cleanup: Having to cleanup texture special://masterprofile/profiles//Thumbnails/Pictures/7/7fbe0dc6.tbn
23:07:19.309 T:3072382752 M:508346368   DEBUG: Cleanup: Having to cleanup texture special://masterprofile/profiles//Thumbnails/Pictures/9/9217aa84.tbn
23:07:19.309 T:3072382752 M:509235200   DEBUG: Cleanup: Having to cleanup texture special://masterprofile/profiles//Thumbnails/Pictures/2/2d87859e.tbn
23:07:19.310 T:3072382752 M:510124032   DEBUG: Cleanup: Having to cleanup texture special://masterprofile/profiles//Thumbnails/Pictures/5/5a6486b1.tbn
23:07:19.310 T:3072382752 M:510885888   DEBUG: Cleanup: Having to cleanup texture special://masterprofile/profiles//Thumbnails/Pictures/0/0e71fc93.tbn
23:07:19.311 T:3072382752 M:511774720   DEBUG: Cleanup: Having to cleanup texture special://masterprofile/profiles//Thumbnails/Pictures/d/d950daad.tbn
23:07:19.312 T:3072382752 M:512663552   DEBUG: Cleanup: Having to cleanup texture special://masterprofile/profiles/e/Thumbnails/Pictures/7/718e111b.tbn
23:07:19.312 T:3072382752 M:513556480   DEBUG: Cleanup: Having to cleanup texture special://masterprofile/profiles/e/Thumbnails/Pictures/7/73db69db.tbn
23:07:19.313 T:3072382752 M:514445312   DEBUG: Cleanup: Having to cleanup texture special://masterprofile/profiles//Thumbnails/Pictures/f/f556eb61.tbn
23:07:19.314 T:3072382752 M:515334144   DEBUG: Cleanup: Having to cleanup texture special://masterprofile/profiles/e/Thumbnails/Pictures/d/dc00efe4.tbn
23:07:19.315 T:3072382752 M:516222976   DEBUG: Cleanup: Having to cleanup texture special://masterprofile/profiles//Thumbnails/Pictures/6/6a161351.tbn
23:07:19.315 T:3072382752 M:517111808   DEBUG: Cleanup: Having to cleanup texture special://masterprofile/profiles//Thumbnails/Pictures/0/03aa6d65.tbn
23:07:19.316 T:3072382752 M:518000640   DEBUG: Cleanup: Having to cleanup texture special://masterprofile/profiles//Thumbnails/Pictures/7/795c5d25.tbn
23:07:19.317 T:3072382752 M:518889472   DEBUG: Cleanup: Having to cleanup texture special://masterprofile/profiles//Thumbnails/Pictures/8/85ccb18f.tbn
23:07:19.318 T:3072382752 M:519786496   DEBUG: Cleanup: Having to cleanup texture button-focused.png
23:07:19.318 T:3072382752 M:519913472   DEBUG: Cleanup: Having to cleanup texture colors/color-grey.png
23:07:19.319 T:3072382752 M:519913472   DEBUG: Cleanup: Having to cleanup texture colors/color-white.png
23:07:19.328 T:3072382752 M:527405056  NOTICE: stop python
23:07:37.229 T:3009334160 M:527396864   DEBUG: CProcessSlowJob::DoWork - Enter function. [server=1][internet=1][IsStoped=0](wdpslow)
23:07:37.230 T:3009334160 M:527396864  NOTICE: Samba is idle. Closing the remaining connections
23:07:37.231 T:3009334160 M:527396864   DEBUG: CProcessSlowJob::DoWork - Exit function. [server=1][internet=1](wdpslow)
23:07:49.829 T:3020204944 M:527413248    INFO: CCheckInternetConnectionJob::DoWork - Checking the internet connection. [server=1][internet=1][ConnectionToInternetChanged=0](offline)
23:07:49.830 T:3020204944 M:527413248   DEBUG: WatchDog::CheckIsConnectedToInternet - Enter function. [server=1][internet=1]. [fromJob=1](offline)(wd)
23:07:50.744 T:3020204944 M:527405056   DEBUG: WatchDog::CheckIsConnectedToInternet - Check [http://7.ping.boxee.tv/] return [1]. [server=1][internet=1]. [fromJob=1](offline)(wd)
23:07:50.744 T:3020204944 M:527405056   DEBUG: WatchDog::CheckIsConnectedToInternet - Exit function and return TRUE. [server=1][internet=1]. [fromJob=1](offline)(wd)

**Comment by FabianMeul** [comment] 2013-01-03 22:52
Also having this issue. This has also been reported by several other users on the Boxee forum.

**Comment by DarkAllMan** [comment] 2013-01-04 12:32
I also noticed this behaviour yesterday!

**Comment by DevlFIG** [comment] 2013-01-05 12:10
I'm having this issue as well.

**Comment by langluc** [comment] 2013-01-05 13:38
me too sometime

**Comment by Oolong666** [comment] 2013-01-06 04:00
Having the same issue just installed v1.4.1.  Sometimes shuts down but usually reboots and requires a hard shutdown to stop.

**Comment by oyvindlille** [comment] 2013-01-06 11:48
Tried to shut down but it didn't. Then i needed to do a hard shutdown since the screen started to flickr. When I started it again, the system was back to fabric standard. Boxeeplus was gone!

**Comment by boxeehacks** [comment] 2013-01-06 23:41
This s a known issue on 1.4.1. And a duplicate of #287 and #262

**Closed as completed by boxeehacks** 2013-01-06 23:41 UTC
