### ISSUE TITLE
Request: Photo Option for Home Screen

### ISSUE THREAD

**Issue by LewisFamily01** [boxeehacks/boxeehack#178] opened 2012-12-11 13:06 UTC
Love the new option of putting Music back on the home page. Is it possible to add Photos also?

**Comment by michske86** [comment] 2012-12-11 17:39
See #150

**Comment by boxeehacks** [comment] 2012-12-17 14:33
Duplicate of #150 as mentioned above by Michske86

**Closed as completed by boxeehacks** 2012-12-17 14:33 UTC
