### ISSUE TITLE
mode for photos

### ISSUE THREAD

**Issue by graysonbt** [boxeehacks/boxeehack#241] opened 2012-12-24 16:22 UTC
I suggest that you create the display mode for photos with thumbnails similar to what was done with the music mode. Would add much to our boxee today that does not have this feature. Congratulations for the beautiful work!

**Comment by boxeehacks** [comment] 2012-12-24 21:41
Duplicate of #178 and #150

**Closed as completed by boxeehacks** 2012-12-24 21:41 UTC
