### ISSUE TITLE
Request: Alphabet Search when within Show/Film/Music

### ISSUE THREAD

**Issue by Kepners** [boxeehacks/boxeehack#331] opened 2013-01-06 22:38 UTC
Request: Alphabet Search when within Show/Film/Music

It would be nice to be able to Tap a Letter on the Boxee Box controller Eg: "T" and all the shows/TV... etc that start with the letter "T" show up or that it highlights the First Show/Film with that Letter. Much like the alphabet highlights from the right of the screen - just saves having to navigate all the way over to it and then down through the alphabet.

Cheers
Keps

**Comment by boxeehacks** [comment] 2013-01-06 23:12
Duplicate of #277, #270, #284. Please check first if an issue doesn't already exist.

**Closed as completed by boxeehacks** 2013-01-06 23:12 UTC
Labels: duplicate
