### ISSUE TITLE
Request-ability to delete??

### ISSUE THREAD

**Issue by tekkietekkie** [boxeehacks/boxeehack#297] opened 2013-01-02 19:35 UTC
any chance of an option to delete a video after its been watched? I use it to watch TV shows and afterwards I am manually deleting the files from my NAS using my IPAD 

ideally after the video was finished it would prompt and ask if you want to delete (like on tivo), knowing this option is not for everyone it would be best if there was an option within the boxee hacks options to turn it on / off

or even after you open the file on the left where it has watch later / share etc if it could be put there it would be ok

**Comment by boxeehacks** [comment] 2013-01-06 23:58
Duplicate of #163

**Closed as completed by boxeehacks** 2013-01-06 23:58 UTC
Labels: duplicate
