### ISSUE TITLE
Hide watched TV episodes and whole shows when all is watched

### ISSUE THREAD

**Issue by BjornB2** [boxeehacks/boxeehack#391] opened 2013-01-21 11:14 UTC
Boxee added the option to hide watched movies, but for no apparent reason they didn't add the same functionality to the TV Shows section.

It would be really nice if watched episodes could be hidden, and when all episodes in a show are watched, that the whole show would be hidden. 

Alternative could be an 'unwatched episodes counter' per show in the overview of the shows.

Thanks

**Comment by gadgetchnnel** [comment] 2013-01-21 18:59
Hiding watched episodes seems like a good idea, but there would need to be a way to quickly turn this off and on when viewing TV shows and not just have an option in the Boxee+Hacks settings. Boxee tends to mark videos as watched as soon as you start watching them.
A few times I have accidentally started watching an episode, realised it was the wrong one and stopped playing after a few seconds, and still found it was marked as watched.
Without the ability to turn off the "hide watched episodes" option without going back to the Boxee+Hacks settings, changing the episode back to unwatched would be very cumbersome.

**Comment by BjornB2** [comment] 2013-01-21 19:09
I would suggest doing it just as Boxee does it for movies: make it an option in the left menu. See attached image. 
![IMG_3969](https://f.cloud.github.com/assets/3328086/84068/0777b22e-63fe-11e2-816e-426fad7aa496.JPG)

**Comment by boxeehacks** [comment] 2013-01-27 16:08
Duplicate of #82 . Please use the search first ;)

**Closed as completed by boxeehacks** 2013-01-27 16:08 UTC
