### ISSUE TITLE
VNC on Boxee Box, is it possible?

### ISSUE THREAD

**Issue by renatotuller** [boxeehacks/boxeehack#227] opened 2012-12-20 12:57 UTC
Running VNC Boxee Box, we can have easier access when organizing the files and even later for features that can be enabled in the future.

With this feature we can even use our tablets to use as display and controller.

Great job staff Boxee Plus.

**Comment by boxeehacks** [comment] 2012-12-20 13:05
Duplicate of #95

**Closed as completed by boxeehacks** 2012-12-20 13:05 UTC
Labels: duplicate
