### ISSUE TITLE
Boxee crashing from screensaver

### ISSUE THREAD

**Issue by xler8r** [boxeehacks/boxeehack#311] opened 2013-01-04 01:06 UTC
I had left my Boxee alone for a while; when I came back and hit the menu button, it froze on the screensaver.
-I haven't been able to reproduce this and it has only occurred once. This had not ever happened before installing Boxee+
-I am not sure as to how long it was on before doing this
-I had previously watched a few tv shows before letting it sit on screensaver.

**Comment by cardassian-tailor** [comment] 2013-01-04 16:09
are you by chance able to reproduce the issue?

**Comment by D34dmeat** [comment] 2013-01-04 19:49
I used to have this problem before boxee+, i had screensaver pointed to my images folder and if i waited long enough (until the moment when boxee automatically shuts off video out ) it would freeze, but since boxee+ and switching to standard (boxee+) screensaver it just works.

**Comment by gadgetchnnel** [comment] 2013-01-04 19:55
The only times I have had this happen are when I have tried to use AirPlay to play something from my iPad on the Boxee Box when the screensaver was active. I don't have the screensaver enabled anymore, as it doesn't really make any difference (I turn the television off when I am not using the Boxee Box).

**Comment by boxeehacks** [comment] 2013-01-06 23:35
I have had this issue loads of times (both before and after the hack) and it was always after having played stuff through Airplay. Sometimes a full day after, but never if I hadn't used Airplay.

Anyway unless you can find specific reproduction steps that only cause it to happen under B+H and not regular Boxee then I'm closing it for now, since it's pretty much outside of our control.

**Closed as completed by boxeehacks** 2013-01-06 23:35 UTC

**Comment by xler8r** [comment] 2013-01-07 02:41
Yea, no worries, I don't have any reproduction steps for you. Cheers!
