### ISSUE TITLE
Homescreen icons

### ISSUE THREAD

**Issue by SendoX** [boxeehacks/boxeehack#272] opened 2012-12-30 22:08 UTC
if I set Navi-x, my local movies are no longer visible. can this be changed?
Better with friends. there should install Navi-x

**Comment by boxeehacks** [comment] 2012-12-31 02:11
There will be an option for something like this in a future release definitely. Didn't get round to it yet though for this release.

**Comment by boxeehacks** [comment] 2012-12-31 02:14
Duplicate of #268

**Closed as completed by boxeehacks** 2012-12-31 02:14 UTC
Labels: enhancement, request, homepage
