### ISSUE TITLE
[QUESTIONS] -Trailer - Thx!

### ISSUE THREAD

**Issue by JGKos** [boxeehacks/boxeehack#197] opened 2012-12-13 19:39 UTC
1st off, thanks to everyone for your work on this.  Its everything this hardware should have been in the 1st place.  I am having a hard time locating answers to my questions, so apologies if this has been asked elsewhere. 

I have used Ember MM to get you library in order, so now I have fanart, trailers, proper imdb data and art work for all my movies.
1. I have my Recently Added to show up on my home screen, which is great.  But I have noticed that the pics displayed there are way to large.  How do I go about getting them sized smaller specifically for displaying here?
2. I have the "newer" remote with the Netflix button, problem is I do not use Netflix.  Is there a way to program this button to use something else?

Thanks again!

JK

**Comment by dmike3** [comment] 2012-12-13 19:47
1.) This is something I feel that needs to be addressed as well.
2.) There is already an option in the settings for you to change this button to a play/pause button instead of Netflix.

**Comment by JGKos** [comment] 2012-12-13 19:55
1. \- cool, thanks
2. \- damn, must have missed that.  This is great news thx!

JK

**Comment by JGKos** [comment] 2012-12-16 03:22
I just decided to add trailers to my Ember MM settings, and now have updated my library.  I dump my db off boxee+, and rescan.  I see the trailers have all been seen, but about 1/4 of them are listed as "unidentified".  Please tell me I do not have to go through all these manually to identify them.....

ideas?

thanks
JK

**Comment by boxeehacks** [comment] 2012-12-17 14:53
Question 1 is a duplicate of #101 
2. is already answered :)

**Closed as completed by boxeehacks** 2012-12-17 14:53 UTC
Labels: request
