### ISSUE TITLE
Nfo files

### ISSUE THREAD

**Issue by rdf123** [boxeehacks/boxeehack#420] opened 2013-01-30 04:26 UTC
I came across this post today while trying to sort out some problems with my nfo files.    see...http://forums.boxee.tv/showthread.php?t=49599.  Would it be possible to have an option to turn this off....such as "use local nfo only" or something?  I am not sure if I am oversimplifying a known problem on how the boxee scrapes its data because I am not really sure on how it all works in the first place. Its so frustrating to do all the work on the nfo files only to read that post the next day and think "all that work for nothing"

**Comment by boxeehacks** [comment] 2013-02-10 13:29
This has been addressed in numerous threads on the Boxee forums. The way to get around this is to simply remove the imdb ID from your NFO. After that it will ignore whatever boxee servers say about the file, and use your NFO data as intended.

**Closed as completed by boxeehacks** 2013-02-10 13:29 UTC
