### ISSUE TITLE
Adding more sources for movies tv etc

### ISSUE THREAD

**Issue by swetoast** [boxeehacks/boxeehack#205] opened 2012-12-15 09:43 UTC
Hey guys

wanted to check if its possible to add more sources to check against for information about episodes etc

sites like
http://www.tv.com/
http://thetvdb.com/
http://www.themoviedb.org/
http://www.allmovie.com/

is this possible or does it require the Intel sdk

**Comment by boxeehacks** [comment] 2012-12-17 12:32
Duplicate of #9

**Closed as completed by boxeehacks** 2012-12-17 12:32 UTC
