### ISSUE TITLE
[request] HD indication

### ISSUE THREAD

**Issue by bgallagher** [boxeehacks/boxeehack#399] opened 2013-01-24 16:56 UTC
Could you you show an icon or a cover overlay indicating if the movie / tv show is HD or not, maybe even ort by quality.

**Comment by Toliver182** [comment] 2013-01-25 11:00
This could be done, however i believe that the resolution would need to be added to the NFO

**Comment by boxeehacks** [comment] 2013-01-27 16:18
Yes this could be done probably. But the info is not present in the Boxee database itself (even though the documentation says it is!) so it will require either specific file naming or special tags in the NFO. This means it's not exactly trivial to add, and since everything is moving to HD anyway, the distinction between HD and SD soon isn't that important anymore. That's why it's not very high on the priority list.

Duplicate of #264, #83, #158

**Closed as completed by boxeehacks** 2013-01-27 16:18 UTC

**Comment by Toliver182** [comment] 2013-01-29 12:48
@boxeehacks what about adding the resolution as a genre? could simplfy things abit... however i do not have one thing in my library that is not HD
