### ISSUE TITLE
Crashing after leaving YouTube app

### ISSUE THREAD

**Issue by fradchad** [boxeehacks/boxeehack#286] opened 2012-12-31 16:20 UTC
The whole system freezes after leaving the YouTube app. This just started with 1.4. On the prior version this piece worked correctly.

**Comment by boxeehacks** [comment] 2013-01-07 00:18
Have you been able to reproduce this more than once? I cannot get this same behaviour. Also please check if you start up the boxee box and use youtube immediately vs. after using airplay (if you have airplay enabled).

**Comment by boxeehacks** [comment] 2013-02-10 12:32
Closing since no feedback given...

**Closed as completed by boxeehacks** 2013-02-10 12:32 UTC
