### ISSUE TITLE
Remove animation at start up

### ISSUE THREAD

**Issue by jairofsouza** [boxeehacks/boxeehack#225] opened 2012-12-19 09:58 UTC
Is it possible to remove the BB animation at boxee start up? By Removing this animation, the boot will be faster?

**Comment by d4yz** [comment] 2012-12-19 13:11
As much as we wished this can be done, its not possible. Our hack doesnt kick in until after that movie is loaded so we cant do anything to remove it at this time.

**Comment by boxeehacks** [comment] 2012-12-20 13:04
Also a duplicate of #215 and #14

**Closed as completed by boxeehacks** 2012-12-20 13:04 UTC
Labels: duplicate
