### ISSUE TITLE
Request: Netflix on the main menu

### ISSUE THREAD

**Issue by greenpasta** [boxeehacks/boxeehack#183] opened 2012-12-11 20:36 UTC
It would be great if we could pull Netflix to the main screen menu.  I could do without "Friends" or even "Watch Later" to make room for it.

**Comment by helgeim** [comment] 2012-12-11 20:44
It would be great if we could replace Friends and Watch Later with Netflix and Spotify (or any other apps) ;)

**Comment by boxeehacks** [comment] 2012-12-11 22:31
Yeah, this pretty much goes for all apps;

partial duplicate of #172
and partial duplicate of #136

Closing and making a new issue for any app on home screen

**Closed as completed by boxeehacks** 2012-12-11 22:31 UTC
