### ISSUE TITLE
Front Page Featured

### ISSUE THREAD

**Issue by NeilJones** [boxeehacks/boxeehack#199] opened 2012-12-13 23:19 UTC
For the front page featured, I have set it to Recently Added however it pulls the covers. This would be ok but the pic ratio makes it look rubbish. How about Fan Art instead?

**Comment by jesseblue** [comment] 2012-12-14 00:22
that would make it slower by having boxee resize a high res pic....for some reason, i sometimes see fanart on my recently added...

**Comment by gadgetchnnel** [comment] 2012-12-15 11:10
I think the best thing may be to change the aspect ratio of the thumbnails displayed there to suit the poster images. This would prevent the cropping which occurs now, and could also allow more items to be displayed without needing to scroll.

**Comment by jesseblue** [comment] 2012-12-16 01:11
so i looked at mine closer...it would show the poster for a half second and then goes to fanart...i have fanart.jpg for all my movies...

**Comment by boxeehacks** [comment] 2012-12-17 14:52
It already uses fanart where it can now, but for TV Shows this is not available outside of the episode list. This is a Boxee restriction and as soon as it is fixed for other places this will automatically be updated.

The aspect ratio change of thumbnails is a duplicate of #101

**Closed as completed by boxeehacks** 2012-12-17 14:52 UTC
