### ISSUE TITLE
Option to automaticlly play next TV episode

### ISSUE THREAD

**Issue by Spudzxcvbnm** [boxeehacks/boxeehack#410] opened 2013-01-27 03:54 UTC
The ability to play all videos in a directory, just like it does with a music directory. Maybe an option to repeat/play once/play next in line.

**Comment by boxeehacks** [comment] 2013-01-27 16:27
Duplicate of #116 . Please use the search first ;)

**Closed as completed by boxeehacks** 2013-01-27 16:27 UTC
