### ISSUE TITLE
Buffering issue 

### ISSUE THREAD

**Issue by Rcarnes911** [boxeehacks/boxeehack#247] opened 2012-12-28 17:22 UTC
for some reason I am having problems streaming H264-MPEG-4 avc videos.  I can take boxee+ off and it will stream perfectly but with Boxee+ on I get constant Buffering. I am running a Windows 7 File share off of Wifi

**Comment by boxeehacks** [comment] 2012-12-29 20:41
Duplicate of #155

**Closed as completed by boxeehacks** 2012-12-29 20:41 UTC
