### ISSUE TITLE
Feature Request: Sleep/Shutdown Timer

### ISSUE THREAD

**Issue by reeps** [boxeehacks/boxeehack#166] opened 2012-12-10 21:20 UTC
Would be nice if the addition of a sleep timer could be added. Whether it tells the boxee box to shut down after completion of a video. Or if it can be given a time (30 mins, 60 mins, 90 mins, etc.) until shut down.

**Comment by dmike3** [comment] 2012-12-13 19:03
This can probably be done. However, can you explain why such a feature is needed?

**Comment by reeps** [comment] 2012-12-13 19:14
When we had cable TV, we would often put the TV on to fall asleep- some background noise. With Boxee, when a show ends, the TV doesn't shut off until the boxee goes into it's screensaver. But even then the boxee doesn't shut down completely and eventually the 'whirring' of the fan starts to drive us nuts in the middle of the night. Plus it would save power.

**Comment by dmike3** [comment] 2012-12-13 19:20
I could put this together, but do you have an idea where this feature would be activated from?

**Comment by reeps** [comment] 2012-12-13 19:24
Cool! that's a good question, I could either see it being like a global variable that no matter what video you're playing or what app you're in, the boxee would shut off after X time. That could be set from the homescreen? You'd have to set it, then continue using the boxee like normal and it would know when to turn off.

Or it could be in the play controls: shut down after this episode.

I know another thread here talks about a playlist feature - so the sleep thing could even fall into that, after playlist has ended - shut down boxee box. But then if you've got a movie on with netflix or something, that wouldn't work. Do you or anyone else have any ideas?

**Comment by dmike3** [comment] 2012-12-13 19:41
Well I could definitely put together something that would shut down no matter what is going on. However, if you wanted it to cancel out if you're in the process of watching something, I can't do this.

Let me know, and I'll put something together when I get time.

**Comment by hessius** [comment] 2012-12-13 20:11
Maybe it could be activated from the overlay menu? (boxee_browse_menu.xml)

**Comment by dmike3** [comment] 2012-12-13 20:17
Sure, let me look into it. As long as I don't get to occupied I'm sure I can get this done. I'm just curious if others would like to see this feature as well before diving in.

**Comment by boxeehacks** [comment] 2012-12-17 15:07
Duplicate of #98

**Closed as completed by boxeehacks** 2012-12-17 15:07 UTC
Labels: duplicate, request
