### ISSUE TITLE
Feature Request - mark watched TV series

### ISSUE THREAD

**Issue by dmnilsson** [boxeehacks/boxeehack#280] opened 2012-12-31 07:56 UTC
I download a lot of TV series, a feature I would love to have is an option to mark watched TV series.

When a episode is watched there is an green check mark.
But when all episodes of a show are watched there aren't anything that indicates that the show doesn't have any new episodes at the TV series selecting screen.

I'd like the same check mark but at the show selecting screen.
Hope you understand my request :)

**Comment by boxeehacks** [comment] 2013-01-07 00:25
You can already mark an entire series as watched or unwatched in the series overview screen.

There is however no checkmark yet for the tv series. This will be added in the future.

Duplicate of #11

**Closed as completed by boxeehacks** 2013-01-07 00:25 UTC
