### ISSUE TITLE
Home.xml Background

### ISSUE THREAD

**Issue by SendoX** [boxeehacks/boxeehack#210] opened 2012-12-16 08:05 UTC
I made it. Edit the Home.xml

You can see here:
http://www.sendox.de/boxee/home2.jpg
![287821_477687578939726_228735711_o](https://f.cloud.github.com/assets/3018141/15395/3959985c-4757-11e2-923d-908dac1d837b.jpg)
![home3](https://f.cloud.github.com/assets/3018141/15413/67fac0a0-4761-11e2-8fb6-69e86d0b5cda.jpg)

**Comment by F33db3ck** [comment] 2012-12-16 18:42
Great, can you share how you did it?

Where to place the file, what format (bmp, jpg, png?) en what to edit in the home.xml

Kind regards.

**Comment by SendoX** [comment] 2012-12-16 19:22
http://www.boxee-forum.de/board34-boxee-box/board95-boxeebox-hacks-custom-firmwares/3081-boxee-box-home-screen-background/#post8516

**Comment by F33db3ck** [comment] 2012-12-16 19:24
Thanx..

**Comment by boxeehacks** [comment] 2012-12-17 13:36
Duplicate of #86

**Closed as completed by boxeehacks** 2012-12-17 13:36 UTC
