### ISSUE TITLE
New Carrousel view missing very important fuction. (no letter right side pop out)

### ISSUE THREAD

**Issue by sphinxlady** [boxeehacks/boxeehack#277] opened 2012-12-31 06:44 UTC
The new view looks great and works without issue but it has one large defect to it.

In the stock views you can go to the options at the time right and move through to a pick and letter option.
Which is rather useful when you have large collections of media.

This no longer works in the new view and considering boxee habit of slowing down media browsing when its refreshing artwork this could cause quite the issue with the new view response time.

Its a small thing but a rather important function.

Ahh fudge this girl missed that people already posted, guess i shouldn't had that lst cooler.

**Comment by jesseblue** [comment] 2012-12-31 19:21
similar to Issue #270

**Comment by boxeehacks** [comment] 2013-01-07 00:30
Duplicate of #270, #331

**Closed as completed by boxeehacks** 2013-01-07 00:30 UTC
