### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by BoxeePlusSupporter** [boxeehacks/boxeehack#160] opened 2012-12-10 11:42 UTC
i'd like to tell or better said suggest you some improvements.
1. studio labels on detail view - very nice. can you add more file info? solution, audio codec, runtime for example? Take a look on ember media manager for example of how it could be designed.
2. more skipping types. its very bad that boxee just can step 10 seconds. would be nice if there's a macro or key binding for skipping like "30sec" or "1min"
3. local scraping for not listed movies and especially tv-shows or anime.
4.  thats not a suggestion, its more like an official boxxe issue: WMV cant be skipped. every time you try, boxee skipps, lagging around and restarts.
5. a problem i have a long time: when using boxee for music, constantly switching the music slows down boxee till freeze. interesting: cpu usage not higher than normally....
6. custom icons made on 1.2.2 wont "disappear" on home screen, even if unchecked in settings, thy still stay on home screen.

greets from Germany
BoxeePlusSupporter

**Comment by bionemesis** [comment] 2012-12-10 20:12
+1 on the skipping types. I prefer XBMC, where right/left arrow skips 30s and up/down skips 10min (they actually use an algorithm to select times best on the length of the video file).

**Comment by SendoX** [comment] 2012-12-11 17:05
Hello. Thank you for the work that you do.
A new background image in the home screen would be nice. Here is an alternate background image for the movie section.
DVD Cover
http://www.sendox.de/boxee/dvd.png

http://www.sendox.de/boxee/dvd2.png
http://www.sendox.de/boxee/bg-browse-overlay%20DVD%20Cover.rar

**Comment by boxeehacks** [comment] 2012-12-17 13:26
Please make a separate issue for each point. It's now difficult to assign things to milestones, or close things, that may be duplicates, because everything is in one issue.
1. is duplicate of #158 
2. could be nice improvement if possible, will need to look into this; please make a separate issue for this
3. you can use something like ember media manager to create local NFOs which allow you to do completely custom types of scraping.
4. This is something in the Boxee executable that we cannot fix :(
5. This is a Boxee issue, and again unfortunately something we cannot fix :(
6. Does this also occur on the latest version? You should upgrade to the latest version 1.3.5 before submitting issues to make sure they haven't already been fixed.

**Closed as completed by boxeehacks** 2012-12-17 13:26 UTC
