### ISSUE TITLE
Request: Fix zoom & pan of photos in screensaver

### ISSUE THREAD

**Issue by zk1212** [boxeehacks/boxeehack#373] opened 2013-01-15 12:07 UTC
This is a long waiting feature. can a fix to the zoom & pan of pictures in screensaver be added?

**Comment by adambiggs** [comment] 2013-01-17 23:42
+1

Also, could the screen saver honor the same settings used for picture slideshows?

**Comment by wftl** [comment] 2013-01-21 16:25
+1 
It would be great to actually be able to see the pictures in the slideshow. The sizing is completely nuts.

**Comment by boxeehacks** [comment] 2013-01-27 15:45
Duplicate of #63

**Comment by boxeehacks** [comment] 2013-01-27 15:45
Please use the search function before adding new issues ;)

**Closed as completed by boxeehacks** 2013-01-27 15:45 UTC
