### ISSUE TITLE
Group Sequels Together

### ISSUE THREAD

**Issue by robraposo** [boxeehacks/boxeehack#317] opened 2013-01-05 05:22 UTC
Hi new to Boxee Box and have been looking to get Boxee+ on my Box. Hope I haven't missed it on the forums but for me the most frustrating thing about the Boxee Box is that it does not group movie sequels together. The Fast and The Furious series for example are all over the place. Hoping that plus adds this functionality that should have been included by Boxee

Keep up the good work guys

**Comment by boxeehacks** [comment] 2013-01-06 23:29
Duplicate of #255

**Closed as completed by boxeehacks** 2013-01-06 23:29 UTC
Labels: duplicate
