### ISSUE TITLE
Adding more scrapers like movie.daum.net

### ISSUE THREAD

**Issue by youngchul76** [boxeehacks/boxeehack#209] opened 2012-12-16 06:29 UTC
Despite multiple complaints about boxee scrapers i don't think it's THAT bad..
The only movies i can't get posters and info for are the korean movies which thumbgen will always pull from movie.daum.net servers.  
Is it possible to add this scraper in the next issue?

**Comment by boxeehacks** [comment] 2012-12-17 13:15
Duplicate of #9

**Closed as completed by boxeehacks** 2012-12-17 13:15 UTC
