### ISSUE TITLE
Home page customization with direct link to pelisalacarta

### ISSUE THREAD

**Issue by saragusa** [boxeehacks/boxeehack#214] opened 2012-12-17 15:17 UTC
It would be spectacular if it were possible to go directly from the boxee+ home page in the favorite streaming server of the famous app pelisalacarta (repository: http://www.mimediacenter.info/boxee;
website: http://blog.tvalacarta.info/plugin-xbmc/pelisalacarta/)....

This is one of the app that, without a doubt, brings out the best use of our beautiful box ...

Thanks...

**Comment by boxeehacks** [comment] 2012-12-17 16:23
Apps are part of the standard Boxee functionality. Any specific apps should be requested in the apps section on the boxee forums (forums.boxee.tv).

Adding apps to the homepage is a duplicate of #188

**Closed as completed by boxeehacks** 2012-12-17 16:23 UTC
Labels: duplicate, invalid

**Comment by saragusa** [comment] 2013-01-11 10:08
Hi.

After the 1.4.1 release I see that, probably, my issue was not understood well.

I wish that, as in "Setting Boxee +" can be inserted between the alternatives for "Movies" the app "Navi-x", it can still choose the app "Pelisalacarta" or, even better, that the link directly to this app is selectable from "Home", maybe instead of "Shows" or "Watch Later" .... 

The problem has not been resolved with the 1.4.0 release, as you announced in
the close Issue #188 ......

Thanks

**Comment by boxeehacks** [comment] 2013-01-11 10:14
Yes it has. In 1.4.0 you can select replacements for movies and shows (which was that issue and has been added). However no it has not been added for your specific app request. This is mostly because it is not an app that most users have access to or will want to use. There are some future plans for more customizations in the apps on the home screen, so I'll keep this in mind for possibly adding then...

**Comment by saragusa** [comment] 2013-01-11 10:27
Thanks anymore....

Inviato da iPhone

Il giorno 11/gen/2013, alle ore 11:14, boxeehacks notifications@github.com ha scritto:

**Comment by boxeehacks** [comment] 2013-01-11 10:35
Just one question by the way. That app that you describe, is that available everywhere in the world? I will need to be able to test it to make it work properly, because some apps work weird (spotify e.g. needed a special hacked version). If I cannot test it will be difficult to include this... Can you let me know?

**Comment by saragusa** [comment] 2013-01-11 10:42
I believe so, yes.

Certainly in Italy, Spain and throughout Europe is one of the most popular streaming apps for Boxee. I added the link in the first post .....

**Comment by saragusa** [comment] 2013-01-11 11:11
In Italy Pelisalacarta definitely works much better than Navi-x and is much more efficient.

See for yourself: install the repository on Boxee and I know about ....
